# Generated by Django 5.2.9 on 2026-01-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(help_text='ID Técnico (ex: iapetus)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nome Interno', max_length=100)),
                ('display_name', models.CharField(help_text='Nome de Exibição', max_length=100)),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20)),
                ('language', models.CharField(default='pt-BR', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True, help_text='Prompt de sistema para estilo')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('demo_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'ordering': ['order', 'display_name'],
            },
        ),
    ]
