# Generated by Django 5.2.9 on 2026-01-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_voiceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='tracks/')),
                ('category', models.CharField(default='Geral', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('duration', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, help_text='Chave Global (Opcional - usuários podem ter a própria)', max_length=255)),
                ('google_client_id', models.CharField(blank=True, max_length=255)),
                ('tts_model', models.CharField(default='gemini-2.5-flash-preview-tts', max_length=100)),
                ('chat_model', models.CharField(default='gemini-2.5-flash', max_length=100)),
                ('specialist_prompt', models.TextField(default='Você é um Especialista em Copywriting...', help_text='Prompt do sistema para o especialista em roteiros')),
                ('site_title', models.CharField(default='Locutando AI', max_length=255)),
                ('hero_headline', models.CharField(default='Crie Locuções de Varejo em Segundos', max_length=255)),
                ('hero_subheadline', models.TextField(default='Inteligência Artificial avançada para gerar vozes ultra-realistas.')),
                ('primary_color', models.CharField(default='#4F46E5', max_length=20)),
                ('evolution_api_url', models.URLField(blank=True, verbose_name='Evolution API URL')),
                ('evolution_api_token', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Configuração Global (IA & Site)',
                'verbose_name_plural': 'Configuração Global (IA & Site)',
            },
        ),
        migrations.DeleteModel(
            name='SystemConfig',
        ),
    ]
