# Generated by Django 5.2.9 on 2026-01-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backgroundtrack_globalconfig_delete_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='supabase_bucket',
            field=models.CharField(default='media', max_length=100, verbose_name='Bucket Storage'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='supabase_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Supabase Public Key'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='supabase_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Supabase URL'),
        ),
    ]
